### ISSUE TITLE
[create] "balance computation failed" improve hover text

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/request-apps#38]
After creating a request, "Unknown" with hover text "The balance computation might have failed" is shown. "Unknown" means that the request has not yet been persisted to IPFS. Thus, I think the text could be improved to help the user understand what is happening.

![image](https://user-images.githubusercontent.com/2530913/202802787-c908a902-7d2b-4dd2-8708-70c3148a02fb.png)

**Comment by MantisClone** [comment]
I later saw the "Unknown" update to "Awaiting Payment".  
![image](https://user-images.githubusercontent.com/2530913/202810952-0910030a-4af8-4bda-aaf6-ae9045c7c1e4.png)


From this I realize that "Unknown" means that the request has not yet been persisted to IPFS. Thus, I think the text could be improved to help the user understand what is happening.

**Comment by PijiDev** [comment]
@MantisClone Suggestion to change 'unknown':
overpaid: 'Overpaid',
waiting: 'Waiting',
...
props.status === 'waiting'
            ? 'The request hasn't been indexed by IPFS yet. Please check back later'
            : ''
...

**Comment by MantisClone** [comment]
Hey @PijiDev I'm having trouble visualizing this change based on you description. Can you just make the change and submit a PR?
