### ISSUE TITLE
Request Create fails to fetch balance for MATIC requests

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/request-apps#60]
# Problem
Display bug: MATIC requests display "Creating Request" forever.

# Analysis
Status is based on request.data.balance.balance but in the case of MATIC requests, the balance is null due to error:

```
"processing response error (body="{\"status\":\"0\",\"message\":\"NOTOK\",\"result\":\"Invalid API Key\"}", error={"result":"{\"status\":\"0\",\"message\":\"NOTOK\",\"result\":\"Invalid API Key\"}"}, requestBody=null, requestMethod="GET", url="https://api.polygonscan.com/api?module=account&action=txlist&address=0x7eB023BFbAeE228de6DC5B92D0BeEB1eDb1Fd567&startblock=0&endblock=99999999&sort=asc&apikey=9D13ZE7XSBTJ94N9BNJ2MA33VMAY2YPIRB", code=SERVER_ERROR, version=web/5.5.0)"
```

![image](https://user-images.githubusercontent.com/2530913/229245919-4c8cb882-ebf4-4e14-99bc-39d6df024b1a.png)

# Solution
Upgrade Request Create app to allow setting a private Polygonscan API key instead of using the default API key provided by ethers

---

Migrated from Asana: https://app.asana.com/0/1203912381456855/1205300974037142/f

**Comment by GHkrishna** [comment]
Hey @MantisClone 

I tried working with the URL. Actually, polygon allows access to transaction data without necessarily providing the API key.

So in this case would the API key be necessary?

We could have a request without the key.

**Comment by MantisClone** [comment]
@GHkrishna If you're able to remove the need for the API key entirely, that would be great. :+1: Just be sure not to break any of the other chains that may still require an API key.

**Comment by MantisClone** [comment]
https://github.com/RequestNetwork/request-apps/issues/67#issuecomment-2085741704
> We decided to deprecate and shut down [Request Create](https://create.request.network/)
